service: my-translation-bot-1

provider:
  name: aws
  stage: dev
  region: ap-northeast-1 #
  runtime: python3.8
  environment:
    LINE_CHANNEL_SECRET: 64acf7907cb6139871e4886cf5b2b904
    LINE_CHANNEL_ACCESS_TOKEN: 3D6CEKbI858siRSxwzoI3Cb9vFzeb9AJBGPHxRDIjvD9v1XxHsv/dY997OQvPyMzHEcqFrLjf6jIIOlPsFfahQKvxi9fVjXwmIve7r7MSM28jgqw6WaFT1fdZKCvjG+xhUZFN2hLub733xXrXYJxOAdB04t89/1O/w1cDnyilFU=
    OPENAI_API_KEY: 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
  iamRoleStatements:
    - Effect: Allow
      Action:
        - translate:TranslateText
      Resource: '*'
    - Effect: Allow
      Action:
        - comprehend:DetectDominantLanguage
      Resource: '*'
functions:
  bot:
    handler: handler.webhook
    events:
      - http:
          path: /webhook
          method: POST
          cors: true
plugins:
  - serverless-python-requirements
